### ISSUE TITLE
[Feature] Possible to use an AWS profile

### ISSUE THREAD

**Issue by 4ureli1** [tenable/EscalateGPT#4]
Hello, for users who utilize AWS profiles in their configuration, we could enhance escalade-GPT to accept a profile as an argument instead of an access key.

Suggestion: Use '--profile "aws_profile"' as an argument.

We should list the roles present in the account linked to the profile, along with their policies.

**Comment by nisani3** [comment]
Thanks, we added support in aws_profile in the new version.
